basePath: /api/v1
definitions:
  types.AuthResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/types.User'
    type: object
  types.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  types.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  types.LogoutRequest:
    properties:
      refresh_token:
        type: string
    type: object
  types.Organization:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
      users:
        items:
          $ref: '#/definitions/types.User'
        type: array
    type: object
  types.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  types.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  types.Response:
    description: Standard API response structure
    properties:
      data:
        description: Actual response data
      error:
        description: |-
          Error message in case of error
          @Example Invalid input parameters
        type: string
      message:
        description: |-
          Optional message providing additional information
          @Example Operation completed successfully
        type: string
      status:
        description: |-
          Status of the response ("success" or "error")
          @Example success
        type: string
    type: object
  types.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_verified:
        type: boolean
      organizations:
        items:
          $ref: '#/definitions/types.Organization'
        type: array
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: raghav@nixopus.com
    name: API Support
    url: http://www.swagger.io/support
  description: Api for Nixopus
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://nixopus.com/terms/
  title: Nixopus Documentation
  version: "1.0"
paths:
  /auth/generate-password-reset-link:
    post:
      consumes:
      - application/json
      description: Generates a password reset link for a user and sends it to the
        user's email
      produces:
      - application/json
      responses:
        "200":
          description: Password reset link sent successfully
          schema:
            $ref: '#/definitions/types.Response'
        "400":
          description: Failed to decode or validate request
          schema:
            $ref: '#/definitions/types.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.Response'
      security:
      - BearerAuth: []
      summary: Generates a password reset link for a user
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with token
          schema:
            allOf:
            - $ref: '#/definitions/types.Response'
            - properties:
                data:
                  $ref: '#/definitions/types.AuthResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/types.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.Response'
      summary: User login endpoint
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out a user by revoking the refresh token.
      parameters:
      - description: Logout request
        in: body
        name: logout
        required: true
        schema:
          $ref: '#/definitions/types.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/types.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/types.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.Response'
      security:
      - BearerAuth: []
      summary: Logout user endpoint
      tags:
      - auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refreshes a users access token with a new one.
      parameters:
      - description: Refresh request
        in: body
        name: refresh
        required: true
        schema:
          $ref: '#/definitions/types.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with token
          schema:
            $ref: '#/definitions/types.AuthResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/types.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/types.Response'
      security:
      - BearerAuth: []
      summary: Refresh token endpoint
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registers a new user in the application.
      parameters:
      - description: Register request
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/types.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with token
          schema:
            $ref: '#/definitions/types.AuthResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/types.Response'
      summary: Register a new user
      tags:
      - auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Resets the user's password using the provided information.
      parameters:
      - description: Reset password request
        in: body
        name: resetPassword
        required: true
        schema:
          $ref: '#/definitions/types.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password reset successfully
          schema:
            $ref: '#/definitions/types.Response'
        "400":
          description: Failed to decode or validate request
          schema:
            $ref: '#/definitions/types.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/types.Response'
      security:
      - BearerAuth: []
      summary: Reset password endpoint
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Enter your bearer token in the format **Bearer &lt;token&gt;**
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
