name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🔧 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧹 Code Style'
    labels:
      - 'style'
      - 'format'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'testing'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'
  - title: '🚨 Breaking Changes'
    labels:
      - 'breaking-change'
      - 'breaking'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## Full Changelog

  $FULL_CHANGELOG

exclude-labels:
  - 'skip-changelog'
  - 'wip'
  - 'draft'

sort-by: 'MERGED_AT'
sort-direction: 'descending'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
  default: 'patch'

filter-by-commitish: true 