// @generated by generate-plugin-routes.js — do not edit
import type { PluginManifest } from './registry';
import plugin0 from './premium/manifest';

export const manifests: PluginManifest[] = [plugin0];
