BEGIN;

ALTER TABLE organization_users
    DROP COLUMN IF EXISTS role_id CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

COMMIT;
