# Workflow: PR Labeler
# Description: Applies labels to pull requests using actions/labeler
# Why: Simplifies PR triage

name: Label PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
    - name: Set up PAT
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: echo "PAT set up"
    - name: Apply PR labels
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}" 
