name: Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
    - name: Set up PAT
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: echo "PAT set up"
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}" 