name: Lint Nixopus API

on:
  pull_request:
    paths:
      - 'api/**'
  push:
    branches:
      - '*'
    paths:
      - 'api/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache: true
          cache-dependency-path: api/go.sum
      
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: api
          args: --timeout=5m